/**
 * DEVELOPMENT / TEST FIXTURES — NOT MARKET DATA.
 *
 * Every candle here is generated by a seeded PRNG. These are synthetic numbers
 * for building and testing the chart workspace; they are not real prices, not
 * derived from any exchange or provider, and must never be presented as market
 * data. The instrument is deliberately named `DEMO/USD` so it cannot be mistaken
 * for a tradable ticker, and `source: 'fixture'` is carried on the series so the
 * UI can label it.
 *
 * NOT REACHABLE FROM PRODUCTION. The real chart path fetches historical candles
 * from the authenticated candles API (docs/CHART_AND_BACKTESTING_DESIGN.md §3).
 * Neither the `/chart` route nor the chart workspace imports this module, and a
 * test enforces that. These fixtures exist for unit tests only.
 *
 * Determinism: the same seed always yields the same series, so tests assert on
 * exact values and the chart looks identical across reloads and machines.
 */
import type { Candle, CandleSeries } from './types';
import { round2 } from './summary';

// Re-exported for the existing fixture tests. `summarizeCandles` itself now
// lives in `./summary` because it is production code — see that module's header.
export { summarizeCandles } from './summary';

/**
 * mulberry32 — a small, fast, fully deterministic PRNG. Chosen over Math.random
 * precisely because fixtures must be reproducible. Not used for anything
 * security-related.
 */
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export const FIXTURE_SEED = 20260719;
export const FIXTURE_SYMBOL = 'DEMO/USD';
export const FIXTURE_INTERVAL = '1h';
/** Bar spacing in seconds (1h), so `time` values are evenly stepped. */
const STEP_SECONDS = 3600;
/** Arbitrary fixed origin so the series never depends on "now". */
const ORIGIN_SECONDS = Date.UTC(2026, 0, 1, 0, 0, 0) / 1000;

/**
 * Generate `count` deterministic OHLCV bars.
 *
 * The walk is bounded and always produces a valid candle: `high` is the max of
 * open/close (plus a wick) and `low` the min (minus a wick), so
 * `low <= min(open,close) <= max(open,close) <= high` holds for every bar —
 * a property the tests assert.
 */
export function generateFixtureCandles(count = 240, seed = FIXTURE_SEED): Candle[] {
  const rand = mulberry32(seed);
  const candles: Candle[] = [];
  let price = 100;

  for (let i = 0; i < count; i++) {
    const drift = (rand() - 0.5) * 2; // [-1, 1)
    const open = price;
    const close = Math.max(1, open + drift);
    const wickUp = rand() * 0.8;
    const wickDown = rand() * 0.8;
    const high = Math.max(open, close) + wickUp;
    const low = Math.max(0.5, Math.min(open, close) - wickDown);
    const volume = Math.round(500 + rand() * 4500);

    candles.push({
      time: ORIGIN_SECONDS + i * STEP_SECONDS,
      open: round2(open),
      high: round2(high),
      low: round2(low),
      close: round2(close),
      volume,
    });
    price = close;
  }
  return candles;
}

/**
 * The development fixture series. Built once per call — callers receive their
 * own array, so a consumer mutating it cannot corrupt anyone else's copy.
 */
export function getFixtureSeries(count = 240): CandleSeries {
  return {
    symbol: FIXTURE_SYMBOL,
    interval: FIXTURE_INTERVAL,
    source: 'fixture',
    candles: generateFixtureCandles(count),
  };
}
