/**
 * AI Coach domain types. An insight is always evidence-grounded: it carries the
 * real figures (from the engines), a confidence derived from sample size, a
 * reasoning summary, and the trades it references (EvidenceLink targets).
 */
import type { CoachTask } from './providers';

export type ReviewScope = 'trade' | 'daily' | 'weekly' | 'monthly';

/** Maps a review scope to the router's task class (cheap vs frontier). */
export const SCOPE_TASK: Record<ReviewScope, CoachTask> = {
  trade: 'trade_review',
  daily: 'daily_review',
  weekly: 'weekly_review',
  monthly: 'monthly_review',
};

/** One engine-computed fact. `value` is pre-formatted for display + prompt. */
export interface SupportingFact {
  label: string;
  value: string;
  /** Raw numeric for reconciliation tests; null when non-numeric/absent. */
  raw: number | null;
}

export type PatternKind =
  | 'overtrading'
  | 'revenge_trading'
  | 'poor_risk_management'
  | 'rule_violation'
  | 'best_condition'
  | 'worst_condition'
  | 'winning_streak'
  | 'losing_streak';

/** A pattern detected deterministically from data (LLM never fabricates these). */
export interface DetectedPattern {
  kind: PatternKind;
  /** Plain, non-shaming description used both in UI and in the prompt. */
  summary: string;
  severity: 'info' | 'watch' | 'attention';
  facts: SupportingFact[];
  referencedTradeIds: string[];
}

export interface Evidence {
  facts: SupportingFact[];
  referencedTradeIds: string[];
  /** 0–100. Reflects data sufficiency, not model certainty. */
  confidence: number;
  /** Human note when confidence is limited (small sample, missing data). */
  confidenceNote: string | null;
}

export interface CoachInsight {
  /** Stable id within a review (for feedback + a11y labelling). */
  id: string;
  scope: ReviewScope;
  /** Model-authored narrative (safety-scrubbed). Numbers come from evidence. */
  narrative: string;
  evidence: Evidence;
  patterns: DetectedPattern[];
}

export interface CoachReview {
  scope: ReviewScope;
  /** Trade id (trade scope) or ISO date/period key (daily/weekly/monthly). */
  targetId: string;
  /** Persisted ai_reviews row id (present once cached; enables feedback). */
  reviewId?: string;
  insights: CoachInsight[];
  model: string;
  provider: string;
  usage: { input: number; output: number };
  /** True when generated by the deterministic mock (no live model configured). */
  mock: boolean;
  generatedAt: string;
}

export interface AIFeedback {
  reviewId: string;
  insightId: string;
  verdict: 'accepted' | 'dismissed';
}
